### ISSUE TITLE
Still being worked on?

### ISSUE THREAD

**Issue by joenot443** [odota/mobile#1]
I'm interested in building a mobile OpenDota application. The developer pointed me in the direction in this project, but I noticed it hasn't been touched in a while. 

Are you still working on it, @Proyoyo?

**Comment by Proyoyo** [comment]
Hey mate, yes I'm still working on it. Work has been pretty busy lately. That's why I haven't worked on it in about 2 months. 

I started a new branch last week trying to upgrade all packages to the latest version. There are still some issues that needs to be worked on before I merge that branch back to master. Feel free to submit pull requests or ask me anything regarding the project. It would be great to get more people to work on the mobile app. 

Regarding features, most basic functionalities to view profile are there. The only thing that needs to be worked on to fulfil MVP is match details page.

**Comment by Proyoyo** [comment]
@joenot443 I just realized that I haven't pushed the RN0.33 branch to this repo. I've pushed it 2 minutes ago.

**Comment by kelset** [comment]
Hey @Proyoyo if you want I can help, I really like RN and I'm using it for my day job too. And ofc I'm full doto so yeah if you want maybe pm me or smth and we can figure out how to make it work ;)

**Comment by Proyoyo** [comment]
@kelset Hey there! Feel free to contribute to this project. I have not had the time to update this repo due to my day job. The best way to reach me will be through the OpenDota's Discord channel: https://discordapp.com/invite/0o5SQGbXuWCNDcaF

The status of the project is still the same as what I mentioned above. Packages need to be updated to be compatible with Android 7 & iOS 10. To fulfil MVP, the only thing that needs to be done is Match Details page.

**Comment by kelset** [comment]
Ok I'll look into this week/weekend - should I look into the master branch or the 0.33? 'cause 0.36 is already out and 0.37 is coming out this week.

**Comment by Proyoyo** [comment]
@kelset Have a look at the 0.33 branch. I'm pretty sure there's no breaking change between 0.33 and 0.37. Feel free to branch out from 0.33 & updated React native version to 0.37 & other packages to their latest compatible version. You should be able to run the 0.33 branch on iOS 10 & Android 7.
