### ISSUE TITLE
package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by cs-miller** [odota/mobile#120]
as far as I know, these two lockfiles are not automatically kept in sync, i.e. yarn does not modify package-lock when it adds a dependency.  Perhaps it is better to just settle on using one or the other?

**Comment by keatongreve** [comment]
+1 to that! It would also be important to create a CONTRIBUTING doc so you can document that one package manager is the preferred for this project, as well as making sure that anyone that wants to contribute with a pull request needs update the preferred lockfile before it can be merged.

FWIW, I really like yarn but I'm usually in favor of keeping npm as the standard for OSS projects, because it is inherently more popular.

**Comment by Proyoyo** [comment]
Personally I've been using npm. However, I have no strong preference for any of the two. Should we use npm because it's what Facebook uses in the React Native tutorial?

**Comment by cs-miller** [comment]
Up to you, just better to pick one and stick with it (afaik) (and delete the unused lockfile).
